### PR TITLE
feat: add banner for doppler plus

### PR DESCRIPTION
**Pull request by GusBaamonde**
Final capture:
banners_doppler-plus

banners

banner-component

#Checklist

- [X] Check if there is a new color.
- [X] Create the color variable in the _colors.scss file.
- [X] Follow the color nomenclature.
- [X] Create the color class with its variable.
- [X] Create the color component in the html, show the name, color class and its exadecimal.

### CODE REVIEW

**Comment by mdirago** [comment]
Nice work Gus! Thank you for the patience :)

**Comment by cbernat** [comment]
A small detail, the banners are not of the same height..
image

**Comment by GusBaamonde** [comment]
> A small detail, the banners are not of the same height..
> image

very fine, but there I saw it I can fix it ;)

**Pull request merged**
