### PR TITLE
feat: remove animation on unexpected error from tables

### PR DESCRIPTION
**Pull request by GusBaamonde**
DW790-sample

@mdirago look!
https://cdn.fromdoppler.com/doppler-ui-library/build1142/subscriber-history.html

DW790-sample2

#Checklist

- [X] Check if there is a new color.
- [X] Create the color variable in the _colors.scss file.
- [X] Follow the color nomenclature.
- [X] Create the color class with its variable.
- [X] Create the color component in the html, show the name, color class and its exadecimal.

### CODE REVIEW

**Comment by andresmoschini** [comment]
Are you sure about the blinking icon? 

This reminds me of those good old times of the [FrontPage](https://es.wikipedia.org/wiki/Microsoft_FrontPage).

**Comment by GusBaamonde** [comment]
> Are you sure about the blinking icon?

hahaha we are removing the animation

**Comment by mdirago** [comment]
> Are you sure about the blinking icon?
> 
> This reminds me of those good old times of the [FrontPage](https://es.wikipedia.org/wiki/Microsoft_FrontPage).
> 
> 

We've just checked it with the Design team and ask Gus to remove the blinking animation :)  The reasons that we've discussed were about consistency and that the animation could be distracting from the reload link.

**Pull request merged**
