### PR TITLE
feat(pagination): adaptation of the paging component

### PR DESCRIPTION
**Pull request by GusBaamonde**
pagination-sample

**No jumps**

sin_saltos_paginacion

**Add title tag**

title-tag

#Checklist

- [X] Check if there is a new color.
- [X] Create the color variable in the _colors.scss file.
- [X] Follow the color nomenclature.
- [X] Create the color class with its variable.
- [X] Create the color component in the html, show the name, color class and its exadecimal.

### CODE REVIEW

**Review by lucianaDilizio — COMMENTED** [review]
👍

**Comment by santiagopaolucci** [comment]
awesome! :)

**Comment by mdirago** [comment]
Great job :)

**Comment by cbernat** [comment]
Very nice!

**Pull request merged**
