### PR TITLE
fix: header nav right to avoid inherit ul styles

### PR DESCRIPTION
**Pull request by fcoronelmakingsense**
- fix header nav right to avoid inherit ul styles in modal on webapp

### CODE REVIEW

**Comment by andresmoschini** [comment]
I think that it is fine, but it would be nice if @GusBaamonde, @damianmuti, @IgnacioRodrigues, @lucianaDilizio, @mvillaseco or @cbernat are better to review this kind of changes.

**Comment by cbernat** [comment]
👍

**Comment by IgnacioRodrigues** [comment]
It's okey Fede! 👍

**Pull request merged**
