### PR TITLE
fix(reports): refactor styles to work fine in traffic sources

### PR DESCRIPTION
**Pull request by fcoronelmakingsense**
- Change styles to be more reusable in all reports box
- Change names of the css classes for reausable proposites

### CODE REVIEW

**Comment by cbernat** [comment]
> Review the space and break space, do you use beautify plugin?

We use prettier here.

**Comment by IgnacioRodrigues** [comment]
> > Review the space and break space, do you use beautify plugin?
> 
> We use prettier here.

Is true! 😁

**Comment by andresmoschini** [comment]
test this please

**Comment by andresmoschini** [comment]
test this please

**Comment by andresmoschini** [comment]
> > > Review the space and break space, do you use beautify plugin?
> > 
> > 
> > We use prettier here.
> 
> Is true! 😁

No, we are not using prettier in UI Library, but we should.

Maybe someone wants to configure it in our build process...

**Comment by cbernat** [comment]
> > > > Review the space and break space, do you use beautify plugin?
> > > 
> > > 
> > > We use prettier here.
> > 
> > 
> > Is true! 😁
> 
> No, we are not using prettier in UI Library, but we should.
> 
> Maybe someone wants to configure it in our build process...

Yes I mistook this for webapp. We should add prettier, althoug it may explode with posibble fixes.

**Comment by andresmoschini** [comment]
test this please

**Comment by andresmoschini** [comment]
test this please

**Pull request merged**
