### PR TITLE
Add .editorconfig file

### PR DESCRIPTION
**Pull request by damianmuti**
Since we don't have a config file to set up different code editors with the same attrs on different environments, and it's actually considered a good practice, I've added a new `.editorconfig` file so we can produce normalized code.

More info here [https://editorconfig.org/](https://editorconfig.org/)

### CODE REVIEW

**Comment by andresmoschini** [comment]
Great @damianmuti!, before merging, let me try to do something to enforce following editor config rules.

**Comment by andresmoschini** [comment]
Sorry @damianmuti, I have parasitized your PR.

I think that it is very important ensuring this kind of rules automatically during CI, so:
* I added verification into CI process
* Added a configuration for comment .scss files
* Deleted redundant file _icon-font.scss
* Fix editorconfig conventions in all of our files.

If you want to fix all the files automatically, you could run 

```bash
./node_modules/.bin/eclint check "**/*"
```

But in general, you will not require it if you have editorconfig support in your text editor.

@IgnacioRodrigues @GusBaamonde @cbernat @mvillaseco @fcoronelmakingsense it could affect you.

**Comment by cbernat** [comment]
> Sorry @damianmuti, I have parasitized your PR.
> 
> I think that it is very important ensuring this kind of rules automatically during CI, so:
> 
> * I added verification into CI process
> * Added a configuration for comment .scss files
> * Deleted redundant file _icon-font.scss
> * Fix editorconfig conventions in all of our files.
> 
> If you want to fix all the files automatically, you could run
> 
> ```shell
> ./node_modules/.bin/eclint fix "**/*"
> ```
> 
> But in general, you will not require it if you have editorconfig support in your text editor.
> 
> @IgnacioRodrigues @GusBaamonde @cbernat @mvillaseco @fcoronelmakingsense it could affect you.

Good to know about this :)

**Comment by damianmuti** [comment]
Don't be sorry, @andresmoschini, it's a true pleasure 🙌

**Comment by andresmoschini** [comment]
🚀

**Comment by IgnacioRodrigues** [comment]
Good work @damianmuti 💯

**Pull request merged**
