### PR TITLE
fix: all subscriber status icons removed

### PR DESCRIPTION
**Pull request by GusBaamonde**
- 1 svg icon was implemented as font
- user status classes were respected to use the icon color
- the legend was added to each icon
- an arial-label and title were added to each icon

#Checklist

- [X] Check if there is a new color.
- [X] Create the color variable in the _colors.scss file.
- [X] Follow the color nomenclature.
- [X] Create the color class with its variable.
- [X] Create the color component in the html, show the name, color class and its exadecimal.

new-icons

### CODE REVIEW

**Comment by cbernat** [comment]
How about adding the description text in the same color of the icon?

**Comment by GusBaamonde** [comment]
> How about adding the description text in the same color of the icon?

We already have many problems of contrast with the design and problems of font sizes for everything that is Accessibility ... I would not color the typography, I think it would negatively impact the readability of each state

**Comment by cbernat** [comment]
👍

**Pull request merged**
