### PR TITLE
Dw 268 semantic release fix

### PR DESCRIPTION
**Pull request by cbernat**
### Fixed semantic release script to be runned into docker container
- Added more steps into dockerfile
- Adjusted build script
- Changed how release script was being executed 
- Now release script executes some tests and builds too for extra check

#Checklist

- [x] Check if there is a new color.
- [x] Create the color variable in the _colors.scss file.
- [x] Follow the color nomenclature.
- [x] Create the color class with its variable.
- [x] Create the color component in the html, show the name, color class and its exadecimal.

### CODE REVIEW

**Comment by cbernat** [comment]
@andresmoschini would you please review just in case 😄

**Comment by cbernat** [comment]
@andresmoschini for now I will leave `gulp dist` task outside docker file. When I learn some more about docker I will get back to change it.

**Comment by andresmoschini** [comment]
👏

**Comment by andresmoschini** [comment]
> @andresmoschini for now I will leave `gulp dist` task outside docker file. When I learn some more about docker I will get back to change it.

Pero no funcionó lo que probamos hoy? avisame y lo vemos juntos estaba casi listo.

**Comment by cbernat** [comment]
> > @andresmoschini for now I will leave `gulp dist` task outside docker file. When I learn some more about docker I will get back to change it.
> 
> Pero no funcionó lo que probamos hoy? avisame y lo vemos juntos estaba casi listo.

Exactamente :)

**Pull request merged**
