### PR TITLE
fix: refactor spinner styles

### PR DESCRIPTION
**Pull request by fcoronelmakingsense**
- Refactor ui library spinner styles to use in webapp to has consistency with doppler app

image

### CODE REVIEW

**Comment by andresmoschini** [comment]
❤️ 

Did you try the grey spinner with a white background? do you have any screenshot or video to share with @santiagopaolucci and ours?

**Comment by fcoronelmakingsense** [comment]
> ❤️
> 
> Did you try the grey spinner with a white background? do you have any screenshot or video to share with @santiagopaolucci and ours?

in Doppler its on white background, i check

**Comment by fcoronelmakingsense** [comment]
image

**Comment by damianmuti** [comment]
Looks good on my end. GJ Fede!

**Comment by andresmoschini** [comment]
Can one of the admins verify this patch?

**Comment by cbernat** [comment]
> Can one of the admins verify this patch?

Who will be the admin here? I don't get what you are trying to say

**Comment by andresmoschini** [comment]
> > Can one of the admins verify this patch?
> 
> Who will be the admin here? I don't get what you are trying to say

Sorry, this message has been written by a Jenkins plugin, see https://wiki.jenkins.io/display/JENKINS/GitHub+pull+request+builder+plugin

I am not sure about the reason, and I have other priorities now. Sorry for the confusion.

**Pull request merged**
