### PR TITLE
Breadcrumb component

### PR DESCRIPTION
**Pull request by GusBaamonde**
The breadcrumb component for Shopify was created

breadcrumb2

### CODE REVIEW

**Comment by cbernat** [comment]
Is it ok having the breadcrumb items divided by `|` instead of '<' as in automation prototypes?

**Comment by GusBaamonde** [comment]
> Is it ok having the breadcrumb items divided by `|` instead of '<' as in automation prototypes?
Let's leave it as in the mockup and anything later we adjust it
http://confluence.makingsense.com/pages/viewpage.action?spaceKey=DOP&title=Shopify+-+Alcance

**Comment by cbernat** [comment]
> > Is it ok having the breadcrumb items divided by `|` instead of '<' as in automation prototypes?
> 
> Let's leave it as in the mockup and anything later we adjust it
> http://confluence.makingsense.com/pages/viewpage.action?spaceKey=DOP&title=Shopify+-+Alcance

I had a different mock up to base my assumptions, the ones in automation --> https://projects.invisionapp.com/d/main#/console/14163830/294817259/preview  anyways let's please check this with @santiagopaolucci

**Comment by santiagopaolucci** [comment]
> > > Is it ok having the breadcrumb items divided by `|` instead of '<' as in automation prototypes?
> > 
> > 
> > Let's leave it as in the mockup and anything later we adjust it
> > http://confluence.makingsense.com/pages/viewpage.action?spaceKey=DOP&title=Shopify+-+Alcance
> 
> I had a different mock up to base my assumptions, the ones in automation --> https://projects.invisionapp.com/d/main#/console/14163830/294817259/preview anyways let's please check this with @santiagopaolucci



> > > Is it ok having the breadcrumb items divided by `|` instead of '<' as in automation prototypes?
> > 
> > 
> > Let's leave it as in the mockup and anything later we adjust it
> > http://confluence.makingsense.com/pages/viewpage.action?spaceKey=DOP&title=Shopify+-+Alcance
> 
> I had a different mock up to base my assumptions, the ones in automation --> https://projects.invisionapp.com/d/main#/console/14163830/294817259/preview anyways let's please check this with @santiagopaolucci

Revisamos esto con Gus y decidimos que va con simbolo ">"

**Comment by GusBaamonde** [comment]
test this please

**Comment by andresmoschini** [comment]
test this please

**Pull request merged**
