### PR TITLE
Gulpfile fix

### PR DESCRIPTION
**Pull request by damianmuti**
Removed a few unnecessary files that were being pushed (and versioned) to GitHub. Aside from that, corrected task dependency for the build and dist tasks.

### CODE REVIEW

**Comment by andresmoschini** [comment]
👍 

Should you also add font files to .git ignore? or they are already included?

**Comment by damianmuti** [comment]
@andresmoschini fonts were already included in the `.gitignore` file, but they were included after commited.

**Comment by andresmoschini** [comment]
🚀

**Pull request merged**
