### PR TITLE
fix(dp-box): remove the overflow-hidden in the box-shadow mixin

### PR DESCRIPTION
**Pull request by GusBaamonde**
#Checklist

- [X] Check if there is a new color.
- [X] Create the color variable in the _colors.scss file.
- [X] Follow the color nomenclature.
- [X] Create the color class with its variable.
- [X] Create the color component in the html, show the name, color class and its exadecimal.

remove-overflow-hidden

### CODE REVIEW

**Comment by andresmoschini** [comment]
❤️  removing code is great!

**Comment by cbernat** [comment]
@GusBaamonde  do you remember why was thi overflow hidden in the first place?

**Comment by GusBaamonde** [comment]
> @GusBaamonde , ¿recuerdas por qué se ocultó este desbordamiento en primer lugar?

If the overflow-hidden was placed so that nothing escapes from the boxes, but just with this graph the tooltip is cut, then it is necessary to remove it

**Comment by andresmoschini** [comment]
> > @GusBaamonde , ¿recuerdas por qué se ocultó este desbordamiento en primer lugar?
> 
> If the overflow-hidden was placed so that nothing escapes from the boxes, but just with this graph the tooltip is cut, then it is necessary to remove it

This teaches us to avoid doing things _just in case_ :)

**Pull request merged**
