### PR TITLE
fix(confirmation page): the relative position of the element was removed…

### PR DESCRIPTION
**Pull request by GusBaamonde**
the relative position of the element was removed for better positioning of the backgrounds

bug-thanks

#Checklist

- [X] Check if there is a new color.
- [X] Create the color variable in the _colors.scss file.
- [X] Follow the color nomenclature.
- [X] Create the color class with its variable.
- [X] Create the color component in the html, show the name, color class and its exadecimal.

### CODE REVIEW

**Comment by GusBaamonde** [comment]
after merging you have to include this version in the webapp

**Comment by andresmoschini** [comment]
👏

**Comment by cbernat** [comment]
👍

**Pull request merged**
